### ISSUE TITLE
IE 11 not rendering discovery.clarin.eu

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/discovery-service-frontend#59]
This was working before, we tested it in 2018 (see https://github.com/clarin-eric/discovery-service-frontend/issues/32)

**Comment by WillemElbers** [comment]
Fixed in:
* https://github.com/clarin-eric/discovery-service-frontend/commit/a4a84b77e8e46457290beadf3f2b858b33fdbf66
* https://github.com/clarin-eric/discovery-service-frontend/commit/4bf3cb08c29649dc3a58077f0d595c34c28dd62c

deployed and tested on https://discovery.clarin-dev.eu (test: https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Fdiscovery.clarin-dev.eu)
